export enum EntityName {
    User = "user",
    Otp = "otp",
    Basket = "basket",
    Category = "category",
    Book = "book",
    Author = "author",
    Publisher = "publisher",
    Season = "season",
    BookOptions = "book_options",
    BookLike = "book_like",
    BookBookmark = "book_bookmark",
    Comment = "comment",
    Order = "order",
    Discount = "discount",
    Payment = "payment",
    Subscription = "subscription",
    Subscribe = "subscribe",
}